"""Add Site model for Wagtail-style homepage configuration."""

depends_on = "0002_page_data"


def upgrade(ctx):
    """Apply migration."""
    ctx.create_table(
        "oxytail_sites",
        fields=[
            {
                "name": "created_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": "CURRENT_TIMESTAMP",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "updated_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": "CURRENT_TIMESTAMP",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "hostname",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": 255,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "port",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "80",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "site_name",
                "python_type": "str",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": 255,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "is_default_site",
                "python_type": "bool",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "locale_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": True,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "root_page_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        indexes=[
            {
                "name": "oxytail_sites_hostname_port_idx",
                "fields": ["hostname", "port"],
                "unique": True,
                "method": None,
            }
        ],
        foreign_keys=[
            {
                "name": "fk_oxytail_sites_locale_id",
                "columns": ["locale_id"],
                "ref_table": "oxytail_locales",
                "ref_columns": ["id"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            },
            {
                "name": "fk_oxytail_sites_root_page_id",
                "columns": ["root_page_id"],
                "ref_table": "oxytail_pages",
                "ref_columns": ["id"],
                "on_delete": "SET NULL",
                "on_update": "CASCADE",
            },
        ],
    )


def downgrade(ctx):
    """Revert migration."""
    ctx.drop_table("oxytail_sites")
