"""Add Image and Rendition models for the media library."""

depends_on = "0003_sites"


def upgrade(ctx):
    """Apply migration."""
    ctx.create_table(
        "oxytail_images",
        fields=[
            {
                "name": "created_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": "CURRENT_TIMESTAMP",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "updated_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": "CURRENT_TIMESTAMP",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "title",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": 255,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "file",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": 512,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "width",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "height",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "focal_point_x",
                "python_type": "float",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "focal_point_y",
                "python_type": "float",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "file_hash",
                "python_type": "str",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": 64,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "file_size",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        indexes=[
            {
                "name": "oxytail_images_title_idx",
                "fields": ["title"],
                "unique": False,
                "method": None,
            }
        ],
        foreign_keys=[],
    )
    ctx.create_table(
        "oxytail_renditions",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "filter_spec",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": 255,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "file",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": 512,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "width",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "height",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "image_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        indexes=[
            {
                "name": "oxytail_renditions_image_filter_spec_idx",
                "fields": ["image_id", "filter_spec"],
                "unique": True,
                "method": None,
            }
        ],
        foreign_keys=[
            {
                "name": "fk_oxytail_renditions_image_id",
                "columns": ["image_id"],
                "ref_table": "oxytail_images",
                "ref_columns": ["id"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
    )


def downgrade(ctx):
    """Revert migration."""
    ctx.drop_table("oxytail_renditions")
    ctx.drop_table("oxytail_images")
